#!/bin/bash
# Rofi interface for bluetooth

case $1 in 
    connect)
        bluetoothctl devices Paired | 
            grep "$(bluetoothctl devices | cut -f3- -d' ' | rofi -show -dmenu -p 'Select device')" | 
            cut -f2 -d' ' | 
            xargs bluetoothctl connect
        ;;
    disconnect)
        bluetoothctl disconnect
        ;;
    *)
        echo "Wrong argument"
        ;;
esac
