#!/bin/bash
# production: true
# Checks how much space is taken by modified/untracked files 
# so you can decide whether it is too much space to track.

is_git=$(git rev-parse --is-inside-work-tree)
if [[ $is_git != "true" ]]; then
    echo "Not a git repo. Try running within a git repo."
    exit 1
fi

size=$(git status --short | 
    awk '{print substr($0,index($0,$2))}' | 
    xargs -n 1 "du" -b | 
    awk '{sum+=($0 + 0)} END {print sum}' | 
    numfmt --to=iec)

echo "Size of modified/untracked files: ${size}b"
