#!/bin/bash
# production: true

curr_level=$(xbacklight -get | awk -F. '{print $1}')
level=$(rofi -dmenu -p "Brightness % (current: $curr_level%)")
if [ $(($?)) -ne 0 ]; then
  exit 0
elif [[ $level =~ ^[0-9]+$ ]]; then
  xbacklight -set $level
else 
  notify-send "brightness-mgr: Please enter an integer."
  exit 1
fi
